name: assssddd

on: push

jobs:
  chromatic-deployment:
    name: Sample
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: echo Hello World
